spring.application.name=api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway manual routes

# Auth Service
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

# Scanner Service - emails
spring.cloud.gateway.routes[1].id=scanner-service-emails
spring.cloud.gateway.routes[1].uri=lb://SCANNER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/emails/**

# Scanner Service - feedback
spring.cloud.gateway.routes[2].id=scanner-service-feedback
spring.cloud.gateway.routes[2].uri=lb://SCANNER-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/feedback/**

# Scanner Service - statistics
spring.cloud.gateway.routes[3].id=scanner-service-statistics
spring.cloud.gateway.routes[3].uri=lb://SCANNER-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/statistics/**

# Audit Service
spring.cloud.gateway.routes[4].id=audit-service
spring.cloud.gateway.routes[4].uri=lb://AUDIT-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/audit/**

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true
ml.service.url=http://localhost:8000